name: build-pages

on: 
  workflow_dispatch:
    inputs:
        wasmreleasetag:
          description: 'wasm_release_tag'
          required: true
          default: build_wasm_2239522285fe7609dfeedb0f5474cc7753408486_6523319742_1

jobs:
    build-pages:
        runs-on: ubuntu-22.04
        steps:
            
            - uses: actions/checkout@v2

            - run: cd $GITHUB_WORKSPACE && npm install && npm run build

            - run: |
                mkdir pages
                cd $GITHUB_WORKSPACE/pages
                mkdir -p example
                cp ../example/* example/
                mkdir -p build/wasm/
                cd build/wasm/
                wget https://github.com/bnw/busytex-async/releases/download/${{ github.event.inputs.wasmreleasetag }}/busytex.wasm
                wget https://github.com/bnw/busytex-async/releases/download/${{ github.event.inputs.wasmreleasetag }}/busytex.js
                cd ../../
                mkdir -p build-js/src/
                cp ../build-js/src/BusytexAsync.browser.js build-js/src/
                mkdir -p typescript/test/assets
                cp ../typescript/test/assets/* typescript/test/assets/

            - uses: actions/upload-pages-artifact@v2
              with:
                path: pages
    
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build-pages
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
